Fix/모달 디자인 수정, 필수 입력값 또는 시간 설정이 잘못될 경우 토스트 메세지 출력
KNU-Develop/todayclothes-frontend pull request #13
Opened 2024-10-02 09:20 UTC by getsoss

# PR Type

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 패키지 의존성 변경, CI/CD, 환경 설정 등

# Overview

모달 디자인 수정, 필수 입력값 또는 시간 설정이 잘못될 경우 토스트 메세지 출력

- todo

# Additional Comment

X

# Issue

X

#XXX

# Check List

- [ ] 관련된 이슈를 연결하였나요?
- [ ] 올바른 PR 컨벤션을 작성했나요?
- [ ] 적절한 라벨을 선택했나요?
- [ ] Assignee와 Reviewer를 설정했나요?

2024-10-02 09:23 UTC, hin6150 commented
This pull request introduces several enhancements to the `PlansModal` component, including the addition of toast notifications for form validation, UI improvements, and minor code cleanups. The most important changes are summarized below:

### Form Validation and Notifications:

* Added `react-toastify` to `package.json` and integrated it into `PlansModal` for displaying error messages when required fields are missing or invalid. (`package.json`, `src/components/PlansModal/PlansModal.tsx`) [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R41) [[2]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR11-R12) [[3]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR89-R131)

### UI Improvements:

* Adjusted the modal layout and styles, including changes to button sizes and input field appearances for better user experience. (`src/components/PlansModal/PlansModal.tsx`) [[1]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dL110-R165) [[2]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR178-R193) [[3]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR207-R222) [[4]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dL157-R234) [[5]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR247-R260) [[6]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dL230-R321) [[7]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dL245-R354)

### Code Cleanups:

* Removed unnecessary comments and improved code readability by restructuring the `handleLog` function and other minor adjustments. (`src/components/PlansModal/PlansModal.tsx`) [[1]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dL40) [[2]](diffhunk://#diff-a6f62313ea12cbc64db7083fdb0739dcd2fabee2529bb60fbacdd4db6781aa4dR146)

2024-10-02 09:43 UTC, seowooda requested changes
이 부분도 이상합니다
![image](https://github.com/user-attachments/assets/5575e7f7-1fe9-4517-b965-b38d79e8c495)


합치시기 전에 저한테 연락주세요.. 제발요 😭

2024-10-02 09:43 UTC, seowooda commented on src/components/PlansModal/PlansModal.tsx
> +                        }}
font 적용X

2024-10-02 09:43 UTC, seowooda commented on src/components/PlansModal/PlansModal.tsx
> +                        }}
font 적용 X

2024-10-02 09:43 UTC, seowooda commented on src/components/PlansModal/PlansModal.tsx
>                  </label>
![image](https://github.com/user-attachments/assets/6ef323e7-9b21-49b4-8f40-7a73f3d9a606)
이 이상한 UI는 뭐죠

2024-10-02 09:43 UTC, seowooda commented on src/components/PlansModal/PlansModal.tsx
> +            <h2 className="mb-[36px] text-center text-[20px] font-semibold leading-normal tracking-[-0.1px]">
폰트 적용이 된건가요..?

2024-10-02 09:43 UTC, seowooda commented on src/components/PlansModal/PlansModal.tsx
> +                  className="flex-1 rounded-[8px] bg-red-100 py-2 text-red-600"
rounded-[8px] 아님, 글씨 이상함

2024-10-05 12:06 UTC, gunhee0421 requested changes
## 문제
현재 전부 toast로 나타납니다. 시간이 잘못 설정된 경우는 toast가 좋은것 같지만, 시간 이외의 필수값인 위치, style, type은 없을경우, 전송 버튼이 disable되는걸로 통일한걸로 기억합니다.
### 즉, 필수 데이터(시간, 위치, style, type)이 하나라도 없다면 전송버튼 disable, 모두 데이터가 들어있지만, 시간 데이터가 현재시간 이전일 경우 버튼은 활성화되지만, toast메세지 출력으로 수정해주세요.

이 부분을 수정하면 될것 같습니다.
### 수고하셨습니다.

2024-10-05 12:07 UTC, gunhee0421 approved these changes

2024-10-07 13:09 UTC, merged