Feat 모달 컴포넌트
KNU-Develop/todayclothes-frontend pull request #8
Opened 2024-09-27 10:05 UTC by getsoss

# PR Type

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 패키지 의존성 변경, CI/CD, 환경 설정 등

# Overview

- todo

# Additional Comment

# Issue

#XXX

# Check List

- [ ] 관련된 이슈를 연결하였나요?
- [ ] 올바른 PR 컨벤션을 작성했나요?
- [ ] 적절한 라벨을 선택했나요?
- [ ] Assignee와 Reviewer를 설정했나요?

2024-09-27 10:46 UTC, gunhee0421 requested changes
수고하셨습니다.
문제 상황은 현재 브랜치에서 수정 후 push하고, 다 수정한 뒤에 합쳐주시면 됩니다.

2024-09-27 10:46 UTC, gunhee0421 commented on .env
> +# NEXT_PUBLIC_MSW='enable'
```suggestion
# NEXT_PUBLIC_MSW='enable'  
NEXT_PUBLIC_MSW='enable'
```
[P1] 현재 api 연결이 안됬기 때문에, msw 테스트가 필요합니다. 활성화해도 잘 돌아가므로 활성화 시켜주세요.

2024-09-27 10:46 UTC, gunhee0421 commented on components/PlansModal.tsx
> +  }>({ lat: null, lng: null })
[P2] 너무 잦은 useState의 반복입니다. useForm으로 개선해주세요.

2024-09-27 10:46 UTC, gunhee0421 commented on src/app/(after)/test/page.tsx
[P3] 현제 페이지를 삭제하고, component/navigationBar에서 RotateCw 클릭시 모달이 오픈되도록 수정해주세요.

2024-09-28 07:55 UTC, seowooda requested changes
모달 전체적인 UI 이상합니다 수정해주세요
![image](https://github.com/user-attachments/assets/3489f14d-cf0a-4ffa-9285-03e3af3c2efe)

2024-09-28 07:55 UTC, seowooda commented on components/PlansModal.tsx
> +                <label className="font-noto-sans-kr text-[12px] font-medium leading-normal text-zinc-400">
폰트 적용 하나도 안되어있습니다..
Noto Sans KR -> `font-notosanko` 로 적용하세요

2024-10-01 06:41 UTC, merged